#!/usr/bin/python2
import os


# get actual path  of the directory this script is in (with all symlinks resolved)
path = os.path.dirname(os.path.realpath(__file__))

os.symlink(path+"/IP-changed", "/usr/local/bin/IP-changed")
os.symlink(path+"/IP-check", "/etc/cron.hourly/IP-check")
